"""update user_rule

Revision ID: a49210c4172b
Revises: e27d4b27b43c
Create Date: 2024-09-30 16:32:27.374613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a49210c4172b'
down_revision: Union[str, None] = 'e27d4b27b43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vip')
    op.drop_table('vip_order')
    op.drop_table('vip_status')
    op.add_column('user_rule', sa.Column('model_name', sa.String(length=50), nullable=False, comment='Model Name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rule', 'model_name')
    op.create_table('vip_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Id'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Member ID'),
    sa.Column('vip_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='VIP ID'),
    sa.Column('level', mysql.INTEGER(), autoincrement=False, nullable=True, comment='VIP level'),
    sa.Column('days', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Days'),
    sa.Column('expiretime', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Expiration time'),
    sa.Column('createtime', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Creation time'),
    sa.Column('status', mysql.ENUM('created', 'active', 'expired', 'finished', 'canceled', 'locked'), nullable=True, comment='Status: created=Unpaid, active=Active, expired=Expired, finished=Completed, canceled=Canceled, locked=Locked'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vip_order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('orderid', mysql.VARCHAR(length=50), nullable=True, comment='Order ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Member ID'),
    sa.Column('vip_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='VIP ID'),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True, comment='Order title'),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='Order amount'),
    sa.Column('payamount', mysql.DECIMAL(precision=10, scale=0), nullable=True, comment='Paid amount'),
    sa.Column('paytype', mysql.VARCHAR(length=50), nullable=True, comment='Payment type'),
    sa.Column('paytime', mysql.INTEGER(), autoincrement=False, nullable=True, comment='Payment time'),
    sa.Column('method', mysql.VARCHAR(length=100), nullable=True, comment='Payment method'),
    sa.Column('ip', mysql.VARCHAR(length=50), nullable=True, comment='IP address'),
    sa.Column('useragent', mysql.VARCHAR(length=255), nullable=True, comment='User Agent'),
    sa.Column('memo', mysql.VARCHAR(length=255), nullable=True, comment='Notes'),
    sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='Creation time'),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True, comment='Update time'),
    sa.Column('status', mysql.ENUM('created', 'paid', 'expired'), nullable=True, comment='Status: created=Unpaid, paid=Paid, expired=Expired'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vip',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Id'),
    sa.Column('level', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='VIP level'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True, comment='Name'),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True, comment='Image'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='Description'),
    sa.Column('price_data', mysql.TEXT(), nullable=True, comment='Price data'),
    sa.Column('right_data', mysql.TEXT(), nullable=True, comment='Right data'),
    sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='Creation time'),
    sa.Column('status', mysql.ENUM('normal', 'hidden', 'pulloff'), nullable=True, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
