"""Initial migration

Revision ID: adf34ccc9860
Revises: 
Create Date: 2024-06-24 09:48:07.092328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf34ccc9860'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon',
    sa.Column('id', sa.Integer(), nullable=False, comment='Id'),
    sa.Column('title', sa.String(length=120), nullable=False, comment='Title'),
    sa.Column('author', sa.String(length=80), nullable=False, comment='Author'),
    sa.Column('uuid', sa.String(length=120), nullable=False, comment='Uuid'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='Description'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='Version'),
    sa.Column('downloads', sa.Integer(), server_default='0', nullable=False, comment='Downloads'),
    sa.Column('download_url', sa.String(length=255), nullable=False, comment='Download_Url'),
    sa.Column('md5_hash', sa.String(length=32), nullable=False, comment='Md5_Hash'),
    sa.Column('price', sa.Numeric(), server_default='0', nullable=True, comment='Price'),
    sa.Column('paid', sa.SmallInteger(), server_default='0', nullable=False, comment='Paid'),
    sa.Column('installed', sa.SmallInteger(), server_default='0', nullable=False, comment='Installed'),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=False, comment='Enabled'),
    sa.Column('createtime', sa.DateTime(), nullable=False, comment='Createtime'),
    sa.Column('updatetime', sa.DateTime(), nullable=False, comment='Updatetime'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('group_id', sa.Integer(), server_default='1', nullable=False, comment='Group Id'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='Username'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='Nickname'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='Password'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Avatar'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='Mobile Number'),
    sa.Column('loginfailure', sa.SmallInteger(), nullable=False, comment='Login Failure Count'),
    sa.Column('logintime', sa.DateTime(), nullable=True, comment='Login Time'),
    sa.Column('loginip', sa.String(length=50), nullable=True, comment='Login IP'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('token', sa.String(length=100), nullable=True, comment='Session Token'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=False, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_group',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), nullable=False, comment='Parent Group'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Group Name'),
    sa.Column('rules', sa.String(length=500), nullable=False, comment='Rule IDs'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=False, comment='Status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_log',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='Administrator ID'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='Administrator Name'),
    sa.Column('url', sa.String(length=1500), nullable=False, comment='Operated Page'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='Log Title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Content'),
    sa.Column('ip', sa.String(length=50), nullable=False, comment='IP Address'),
    sa.Column('useragent', sa.String(length=255), nullable=True, comment='User Agent'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Operation Time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_rule',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('type', sa.Enum('menu', 'action'), nullable=False, comment='Type'),
    sa.Column('pid', sa.Integer(), nullable=False, comment='PARENT ID'),
    sa.Column('addon', sa.SmallInteger(), nullable=False, comment='From Addon'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Route Name'),
    sa.Column('url_path', sa.String(length=50), nullable=False, comment='Url_Path'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='Title'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Description'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Icon'),
    sa.Column('menutype', sa.Enum('addtabs', 'blank', 'dialog', 'ajax'), nullable=True, comment='Menutype'),
    sa.Column('extend', sa.String(length=255), nullable=True, comment='Extend'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Createtime'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Updatetime'),
    sa.Column('weigh', sa.Integer(), nullable=False, comment='Weigh'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=False, comment='Status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment_file',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='GeneralCategory'),
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='Administrator ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Member ID'),
    sa.Column('path_file', sa.String(length=255), nullable=False, comment='Physical Path'),
    sa.Column('file_name', sa.String(length=100), nullable=True, comment='File Name'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File Size'),
    sa.Column('mimetype', sa.String(length=100), nullable=True, comment='MIME Type'),
    sa.Column('extparam', sa.String(length=255), nullable=True, comment='Passthrough Data'),
    sa.Column('createtime', sa.DateTime(), nullable=False, comment='Createtime'),
    sa.Column('updatetime', sa.DateTime(), nullable=False, comment='Update Time'),
    sa.Column('storage', sa.String(length=100), nullable=False, comment='Storage Location'),
    sa.Column('sha1', sa.String(length=40), nullable=True, comment='SHA1 Hash of the File'),
    sa.Column('general_attachmentcol', sa.String(length=45), nullable=True, comment='General Attachmentcol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment_image',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='GeneralCategory'),
    sa.Column('admin_id', sa.Integer(), nullable=False, comment='Administrator ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Member ID'),
    sa.Column('path_image', sa.String(length=255), nullable=False, comment='Physical Path'),
    sa.Column('image_width', sa.String(length=30), nullable=True, comment='Image Width'),
    sa.Column('image_height', sa.String(length=30), nullable=True, comment='Image Height'),
    sa.Column('image_type', sa.String(length=30), nullable=True, comment='Image Type'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='File Name'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File Size'),
    sa.Column('mimetype', sa.String(length=100), nullable=True, comment='MIME Type'),
    sa.Column('extparam', sa.String(length=255), nullable=True, comment='Passthrough Data'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('storage', sa.String(length=100), nullable=True, comment='Storage Location'),
    sa.Column('sha1', sa.String(length=40), nullable=True, comment='SHA1 Hash of the File'),
    sa.Column('general_attachmentcol', sa.String(length=45), nullable=True, comment='General Attachmentcol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_ems',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('event', sa.String(length=30), nullable=True, comment='Event'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Email Address'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='Verification Code'),
    sa.Column('times', sa.Integer(), nullable=False, comment='Validation Attempts'),
    sa.Column('ip', sa.String(length=30), nullable=True, comment='IP Address'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_sms',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('event', sa.String(length=30), nullable=True, comment='Event'),
    sa.Column('mobile', sa.String(length=20), nullable=True, comment='Phone Number'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='Verification Code'),
    sa.Column('times', sa.Integer(), nullable=False, comment='Validation Attempts'),
    sa.Column('ip', sa.String(length=30), nullable=True, comment='IP Address'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_category',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), nullable=False, comment='Parent ID'),
    sa.Column('type', sa.String(length=30), nullable=False, comment='GeneralCategory Type'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='Name'),
    sa.Column('image', sa.String(length=100), nullable=True, comment='Image'),
    sa.Column('keywords', sa.String(length=255), nullable=True, comment='Keywords'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Description'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('weigh', sa.Integer(), nullable=False, comment='Weight'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=False, comment='Status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_config',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='Variable Name'),
    sa.Column('group', sa.String(length=30), nullable=False, comment='Group'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Variable Title'),
    sa.Column('tip', sa.String(length=100), nullable=True, comment='Variable Description'),
    sa.Column('type', sa.String(length=30), nullable=True, comment='Type: string, text, int, bool, array, datetime, date, file'),
    sa.Column('visible', sa.String(length=255), nullable=True, comment='Visibility Condition'),
    sa.Column('value', sa.Text(), nullable=True, comment='Variable Value'),
    sa.Column('content', sa.Text(), nullable=True, comment='Variable Dictionary Data'),
    sa.Column('rule', sa.String(length=100), nullable=True, comment='Validation Rule'),
    sa.Column('extend', sa.String(length=255), nullable=True, comment='Extended Attributes'),
    sa.Column('setting', sa.String(length=255), nullable=True, comment='Settings'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_group_id', sa.Integer(), nullable=False, comment='Group ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='Username'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='Nickname'),
    sa.Column('password', sa.String(length=120), nullable=False, comment='Password'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Email'),
    sa.Column('mobile', sa.String(length=16), nullable=False, comment='Mobile Phone Number'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='Avatar'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='Level'),
    sa.Column('gender', sa.Enum('female', 'male'), nullable=False, comment='Gender'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='Date of Birth'),
    sa.Column('bio', sa.String(length=100), nullable=True, comment='Motto'),
    sa.Column('balance', sa.Numeric(), nullable=True, comment='Balance'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Points'),
    sa.Column('successions', sa.Integer(), nullable=False, comment='Consecutive Login Days'),
    sa.Column('maxsuccessions', sa.Integer(), nullable=False, comment='Maximum Consecutive Login Days'),
    sa.Column('prevtime', sa.DateTime(), nullable=True, comment='Previous Login Time'),
    sa.Column('logintime', sa.DateTime(), nullable=True, comment='Login Time'),
    sa.Column('loginip', sa.String(length=50), nullable=True, comment='Login IP Address'),
    sa.Column('loginfailure', sa.SmallInteger(), nullable=False, comment='Failed Login Attempts'),
    sa.Column('joinip', sa.String(length=50), nullable=True, comment='Joining IP Address'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('verification', sa.String(length=255), nullable=True, comment='Verification'),
    sa.Column('token', sa.String(length=50), nullable=True, comment='Token'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=True, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_balance_log',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Member ID'),
    sa.Column('balance', sa.Numeric(), nullable=False, comment='Change in Balance'),
    sa.Column('before', sa.Numeric(), nullable=False, comment='Balance Before Change'),
    sa.Column('after', sa.Numeric(), nullable=False, comment='Balance After Change'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='Memo/Note'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='Group Name'),
    sa.Column('rules', sa.String(length=512), nullable=True, comment='Permission Nodes'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=False, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_recharge_order',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('trade_no', sa.String(length=100), nullable=True, comment='Trade No'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'),
    sa.Column('amount', sa.Numeric(), nullable=True, comment='amount'),
    sa.Column('pay_amount', sa.Integer(), nullable=True, comment='Pay Amount'),
    sa.Column('transaction_id', sa.String(length=120), nullable=True, comment='Transaction_Id'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='Payment Method'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='Pay Time'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('useragent', sa.String(length=255), nullable=True, comment='UserAgent'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='Memo'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time '),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('status', sa.Enum('created', 'paid', 'expired'), server_default='created', nullable=True, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_no')
    )
    op.create_table('user_rule',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), nullable=False, comment='Parent ID'),
    sa.Column('type', sa.Enum('menu', 'action'), nullable=False, comment='Type'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Route Name'),
    sa.Column('url_path', sa.String(length=150), nullable=False, comment='Url Path'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='Title'),
    sa.Column('icon', sa.String(length=45), nullable=True, comment='Icon'),
    sa.Column('description', sa.String(length=100), nullable=True, comment='Description'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='Update Time'),
    sa.Column('weigh', sa.Integer(), nullable=True, comment='Weight'),
    sa.Column('status', sa.Enum('normal', 'hidden'), server_default='normal', nullable=True, comment='Status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_score_log',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Member ID'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Change in Scores'),
    sa.Column('before', sa.Integer(), nullable=False, comment='Points Before Change'),
    sa.Column('after', sa.Integer(), nullable=False, comment='Points After Change'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='Memo/Note'),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='Creation Time'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_score_log')
    op.drop_table('user_rule')
    op.drop_table('user_recharge_order')
    op.drop_table('user_group')
    op.drop_table('user_balance_log')
    op.drop_table('user')
    op.drop_table('general_config')
    op.drop_table('general_category')
    op.drop_table('common_sms')
    op.drop_table('common_ems')
    op.drop_table('attachment_image')
    op.drop_table('attachment_file')
    op.drop_table('admin_rule')
    op.drop_table('admin_log')
    op.drop_table('admin_group')
    op.drop_table('admin')
    op.drop_table('addon')
    # ### end Alembic commands ###
