"""删除图片模型，将图片合并到文件

Revision ID: b055d7321a62
Revises: adf34ccc9860
Create Date: 2024-09-10 10:24:34.648917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b055d7321a62'
down_revision: Union[str, None] = 'adf34ccc9860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment_image')
    op.drop_index('uuid', table_name='addon')
    op.drop_table('addon')
    op.drop_index('name', table_name='user_group')
    op.drop_index('name', table_name='user_rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user_rule', ['name'], unique=True)
    op.create_index('name', 'user_group', ['name'], unique=True)
    op.create_table('addon',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='Id'),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=False, comment='Title'),
    sa.Column('author', mysql.VARCHAR(length=80), nullable=False, comment='Author'),
    sa.Column('uuid', mysql.VARCHAR(length=120), nullable=False, comment='Uuid'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False, comment='Description'),
    sa.Column('version', mysql.VARCHAR(length=50), nullable=False, comment='Version'),
    sa.Column('downloads', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Downloads'),
    sa.Column('download_url', mysql.VARCHAR(length=255), nullable=False, comment='Download_Url'),
    sa.Column('md5_hash', mysql.VARCHAR(length=32), nullable=False, comment='Md5_Hash'),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=0), server_default=sa.text("'0'"), nullable=True, comment='Price'),
    sa.Column('paid', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Paid'),
    sa.Column('installed', mysql.SMALLINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Installed'),
    sa.Column('enabled', mysql.SMALLINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='Enabled'),
    sa.Column('createtime', mysql.DATETIME(), nullable=False, comment='Createtime'),
    sa.Column('updatetime', mysql.DATETIME(), nullable=False, comment='Updatetime'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uuid', 'addon', ['uuid'], unique=True)
    op.create_table('attachment_image',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=True, comment='GeneralCategory'),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Administrator ID'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Member ID'),
    sa.Column('path_image', mysql.VARCHAR(length=255), nullable=False, comment='Physical Path'),
    sa.Column('image_width', mysql.VARCHAR(length=30), nullable=True, comment='Image Width'),
    sa.Column('image_height', mysql.VARCHAR(length=30), nullable=True, comment='Image Height'),
    sa.Column('image_type', mysql.VARCHAR(length=30), nullable=True, comment='Image Type'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='File Name'),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False, comment='File Size'),
    sa.Column('mimetype', mysql.VARCHAR(length=100), nullable=True, comment='MIME Type'),
    sa.Column('extparam', mysql.VARCHAR(length=255), nullable=True, comment='Passthrough Data'),
    sa.Column('createtime', mysql.DATETIME(), nullable=True, comment='Creation Time'),
    sa.Column('updatetime', mysql.DATETIME(), nullable=True, comment='Update Time'),
    sa.Column('storage', mysql.VARCHAR(length=100), nullable=True, comment='Storage Location'),
    sa.Column('sha1', mysql.VARCHAR(length=40), nullable=True, comment='SHA1 Hash of the File'),
    sa.Column('general_attachmentcol', mysql.VARCHAR(length=45), nullable=True, comment='General Attachmentcol'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
