"""update admin_rule

Revision ID: e27d4b27b43c
Revises: 4ec4e6cd7eb4
Create Date: 2024-09-26 09:07:15.275788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27d4b27b43c'
down_revision: Union[str, None] = '4ec4e6cd7eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_rule', sa.Column('model_name', sa.String(length=50), nullable=False, comment='Model Name'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_rule', 'model_name')
    # ### end Alembic commands ###
